version: '3.2'
services:
  legacywebshop:
    image: docker.io/library/legacywebshop
    depends_on:
      - web-shop-db-image
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  web-shop-db-image:
    image: docker.io/library/local-database
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      - "./data-volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image
  product-ms:
    image: docker.io/library/product-ms
    restart: always
    depends_on:
      - web-shop-db-image
    ports:
      - "8887:8080"
    networks:
      local_dev_net:
        aliases:
          - product-ms
  category-ms:
    image: docker.io/library/category-ms
    restart: always
    depends_on:
      - web-shop-db-image
    ports:
      - "8886:8080"
    networks:
      local_dev_net:
        aliases:
          - category-ms
networks:
  local_dev_net:
    driver: bridge
