apiVersion: v1
kind: Service
metadata:
  name: category-ms
  labels:
    app: category-ms
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: category-ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-ms
  labels:
    app: category-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: category-ms
  template:
    metadata:
      labels:
        app: category-ms
    spec:
      containers:
        - image: localhost:5000/category-ms
          name: category-ms
          ports:
            - containerPort: 8080
