apiVersion: v1
kind: Service
metadata:
  name: legacy-webshop
  labels:
    app: legacy-webshop
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: legacy-webshop
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-webshop
  labels:
    app: legacy-webshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-webshop
  template:
    metadata:
      labels:
        app: legacy-webshop
    spec:
      containers:
        - image: mavogel/hska-vis-legacywebshop
          name: legacy-webshop
          ports:
            - containerPort: 8080
