apiVersion: v1
kind: Service
metadata:
  name: rproxy
  labels:
    app: rproxy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rproxy
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rproxy
  name: rproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rproxy
  template:
    metadata:
      labels:
        app: rproxy
    spec:
      containers:
      - image: localhost:5000/rproxy
        name: rproxy
        ports:
        - containerPort: 80
